Implemented API versioning
biosharp-dotnet/sucuri-api pull request #24
Opened 2022-08-17 12:05 UTC by Aryan-sharma11

Hey,  his pull request is regarding https://github.com/biosharp-dotnet/sucuri-api/issues/19 

- Right now I have restructured the Private folder to store scripts for the different versions of API 

- Now we can use version 1 using  `..\v1\search?pkg_name=<package_name>`

Please, suggest any changes  and improvements that are needed

Kindly, Aryan

2022-08-18 09:42 UTC, abhi18av requested changes
Thanks @Aryan-sharma11 , this is looking good.


The OpenAPI spec is reflecting the changes ✅ 

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/12799326/185363876-14a49e9c-27bf-4665-82a7-69e8a6c7f314.png">


Just one minor change regarding the doc message which needs to be improved - it should include the link for OpenAPI as well

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/12799326/185363597-02cdc987-455f-4806-bf8c-ed63cc29dbcf.png">

2022-08-19 11:57 UTC, Aryan-sharma11 commented
> Thanks @Aryan-sharma11 , this is looking good.
> 
> The OpenAPI spec is reflecting the changes ✅
> 
> <img alt="image" width="1266" src="https://user-images.githubusercontent.com/12799326/185363876-14a49e9c-27bf-4665-82a7-69e8a6c7f314.png">
> 
> Just one minor change regarding the doc message which needs to be improved - it should include the link for OpenAPI as well
> 
> <img alt="image" width="1073" src="https://user-images.githubusercontent.com/12799326/185363597-02cdc987-455f-4806-bf8c-ed63cc29dbcf.png">

@abhi18av I have addressed this issue in https://github.com/biosharp-dotnet/sucuri-api/pull/25

2022-08-19 13:28 UTC, abhi18av requested changes
Requested some changes - but nothing breaking.

2022-08-19 13:28 UTC, abhi18av commented on Sucuri-API/Public/Start-SucuriServer.ps1
> +      $serverName = "$env:COMPUTERNAME:8085/docs/v1"
```suggestion
      $serverName = "$env:COMPUTERNAME:8085/docs/v1"

```
This does not exist on non-windows machine - let's not change this.

2022-08-19 13:28 UTC, abhi18av commented on Sucuri-API/Public/Start-SucuriServer.ps1
@Aryan-sharma11 , let's keep the `docs` endpoint away from `v1/v2` etc.

2022-08-19 13:30 UTC, merged